name: 'Run Transformer'
description: 'Runs the transformer.'
inputs:
  xform-command:
    description: 'The command to execute the transformer.'
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.xform-command }}
